name: Notify Discord on push

on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: |
            🚀 Push to `${{ github.ref_name }}`
            📝 Commit:
            ```
            ${{ github.event.head_commit.message }}
            ```
